grsec: Apply grsecurity-3.0-3.14.1-201404241722.patch
commit 0315786960600005ba56ac24ac020efc8f698d0f
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Wed Apr 16 14:25:16 2014 +0300

    Upstream commit: b7a314054eb55e3745a9409beaa5d8be5cd2d273

    isdn: icn: buffer overflow in icn_command()

    This buffer over was detected using static analysis:

    	drivers/isdn/icn/icn.c:1325 icn_command()
    	error: format string overflow. buf_size: 60 length: 98

    The calculation for the length of the string is off because it assumes
    that the dial[] buffer holds a 50 character string, but actually it is
    at most 31 characters and NUL.  I have removed the dial[] buffer because
    it isn't needed.

    The maximum length of the string is actually 79 characters and a NUL.  I
    have made the cbuf[] array large enough to hold it and changed the
    sprintf() to an snprintf() as a further safety enhancement.

    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

 drivers/isdn/icn/icn.c |   11 +++++------
 1 files changed, 5 insertions(+), 6 deletions(-)

commit b0dff0371d218b1a0f94f93684abe16ce56ba384
Author: Eric Dumazet <edumazet@google.com>
Date:   Sat Apr 19 10:15:07 2014 -0700

    Upstream commit: 404ca80eb5c2727d78cd517d12108b040c522e12

    coredump: fix va_list corruption

    A va_list needs to be copied in case it needs to be used twice.

    Thanks to Hugh for debugging this issue, leading to various panics.

    Tested:

      lpq84:~# echo "|/foobar12345 %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h" >/proc/sys/kernel/core_pattern

    'produce_core' is simply : main() { *(int *)0 = 1;}

      lpq84:~# ./produce_core
      Segmentation fault (core dumped)
      lpq84:~# dmesg | tail -1
      [  614.352947] Core dump to |/foobar12345 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 lpq84 (null) pipe failed

    Notice the last argument was replaced by a NULL (we were lucky enough to
    not crash, but do not try this on your production machine !)

    After fix :

      lpq83:~# echo "|/foobar12345 %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h %h" >/proc/sys/kernel/core_pattern
      lpq83:~# ./produce_core
      Segmentation fault
      lpq83:~# dmesg | tail -1
      [  740.800441] Core dump to |/foobar12345 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 lpq83 pipe failed

    Fixes: 5fe9d8ca21cc ("coredump: cn_vprintf() has no reason to call vsnprintf() twice")
    Signed-off-by: Eric Dumazet <edumazet@google.com>
    Diagnosed-by: Hugh Dickins <hughd@google.com>
    Acked-by: Oleg Nesterov <oleg@redhat.com>
    Cc: Neil Horman <nhorman@tuxdriver.com>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Cc: stable@vger.kernel.org # 3.11+
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

 fs/coredump.c |    7 ++++++-
 1 files changed, 6 insertions(+), 1 deletions(-)

commit d6238568d6f2ffd112bda2a5dcc8b1c055ab5eef
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Tue Apr 22 13:49:40 2014 -0700

    Upstream commit: 1b17844b29ae042576bea588164f2f1e9590a8bc

    mm: make fixup_user_fault() check the vma access rights too

    fixup_user_fault() is used by the futex code when the direct user access
    fails, and the futex code wants it to either map in the page in a usable
    form or return an error.  It relied on handle_mm_fault() to map the
    page, and correctly checked the error return from that, but while that
    does map the page, it doesn't actually guarantee that the page will be
    mapped with sufficient permissions to be then accessed.

    So do the appropriate tests of the vma access rights by hand.

    [ Side note: arguably handle_mm_fault() could just do that itself, but
      we have traditionally done it in the caller, because some callers -
      notably get_user_pages() - have been able to access pages even when
      they are mapped with PROT_NONE.  Maybe we should re-visit that design
      decision, but in the meantime this is the minimal patch. ]

    Found by Dave Jones running his trinity tool.

    Reported-by: Dave Jones <davej@redhat.com>
    Acked-by: Hugh Dickins <hughd@google.com>
    Cc: stable@vger.kernel.org
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

 mm/memory.c |    5 +++++
 1 files changed, 5 insertions(+), 0 deletions(-)

commit c30687b3dc4a23853c179b365d4c5b003f768f80
Author: Brad Spengler <spender@grsecurity.net>
Date:   Wed Apr 23 20:19:43 2014 -0400

    fix RANDSTRUCT compilation on arm allyesconfig

 drivers/video/sh_mobile_lcdcfb.c |    6 +++---
 1 files changed, 3 insertions(+), 3 deletions(-)

commit 480fa0cf384348cc476b719836bc94bab5b6c2d6
Author: Brad Spengler <spender@grsecurity.net>
Date:   Wed Apr 23 20:04:53 2014 -0400

    compile fix: we renamed object_is_on_stack to (the more accurate)
    object_starts_on_stack

 drivers/mtd/nand/gpmi-nand/gpmi-nand.c |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

commit fd5d587eb3cb7f64bdc925b508dc7ae8e7540684
Merge: 1884701 966aa1c
Author: Brad Spengler <spender@grsecurity.net>
Date:   Wed Apr 23 19:06:10 2014 -0400

    Merge branch 'pax-test' into grsec-test

commit 966aa1c686ea4bff7eac840c8e292a5661059dc8
Author: Brad Spengler <spender@grsecurity.net>
Date:   Wed Apr 23 19:04:54 2014 -0400

    Update to pax-linux-3.14.1-test6.patch:
    - spender fixed various compilation problems on arm, reported by Michael Tremer
    - spender fixed a sparc compile error
    - changed the colorize plugin to be similar to -fdiagnostics-color in gcc 4.9
      - http://gcc.gnu.org/onlinedocs/gcc-4.9.0/gcc/Language-Independent-Options.html
      - by default colorization is off
      - if GCC_COLORS exists in the environment then stderr will be colored if it's a terminal
      - -fplugin-arg-colorize_plugin-color= takes the same arguments as -fdiagnostics-color=
        - e.g., the old behaviour is equivalent to EXTRA_CFLAGS=-fplugin-arg-colorize_plugin-color=always
      - the value of GCC_COLORS isn't parsed yet, the existing colors (red/yellow/blue) are used instead
    - fixed all warnings on the gcc plugins reported by clang
    - fixed a REFCOUNT regression that would instrument code even when REFCOUNT was disabled

 Makefile                           |    2 +-
 arch/arm/include/asm/mach/map.h    |    4 +-
 arch/arm/mm/mmu.c                  |    4 +-
 arch/arm/plat-iop/setup.c          |    2 +-
 arch/sparc/mm/hugetlbpage.c        |    1 +
 arch/x86/include/asm/cmpxchg.h     |    4 ++
 arch/x86/kernel/traps.c            |    4 +-
 drivers/dma/sh/shdma-base.c        |    4 +-
 drivers/gpu/drm/tegra/dsi.c        |    2 +-
 drivers/irqchip/irq-renesas-irqc.c |    2 +-
 drivers/thermal/of-thermal.c       |   13 ++++--
 tools/gcc/colorize_plugin.c        |   77 +++++++++++++++++++++++++++--------
 tools/gcc/constify_plugin.c        |   13 ++++--
 tools/gcc/kallocstat_plugin.c      |    9 ++--
 tools/gcc/kernexec_plugin.c        |   27 +++++++------
 tools/gcc/latent_entropy_plugin.c  |   13 ++++--
 tools/gcc/size_overflow_plugin.c   |   27 +++++++------
 tools/gcc/stackleak_plugin.c       |   18 +++++----
 tools/gcc/structleak_plugin.c      |    9 ++--
 19 files changed, 154 insertions(+), 81 deletions(-)

commit 188470114e75fba3505dcf6722cf65fd04a1a974
Author: Brad Spengler <spender@grsecurity.net>
Date:   Sun Apr 20 17:00:14 2014 -0400

    fix allmodconfig compilation

 drivers/usb/gadget/f_uac1.c |    1 +
 1 files changed, 1 insertions(+), 0 deletions(-)

commit c960a617471b908413a489019c60a7b644127708
Author: Brad Spengler <spender@grsecurity.net>
Date:   Sun Apr 20 16:59:15 2014 -0400

    fix allmodconfig compilation

 drivers/usb/gadget/u_uac1.c |    1 +
 1 files changed, 1 insertions(+), 0 deletions(-)

Signature-tree: 7587a45584558886208c2dcccab2752b42b83605